config/routes.rb
Rails.application.routes.draw do
  root "pay_periods#calendar"

  resources :pay_periods do
    member do
      post :update_with_adjacent_pay_periods
    end
    collection do
      get :calendar
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/icon.rb
class Icon
  LOOKUP_MAP = {
    add: "square-plus",
    alert: "circle-xmark",
    delete: "trash-can",
    edit: "pen-to-square",
    go_left: "circle-left",
    go_right: "circle-right",
    notice: "circle-check",
  }

  def initialize(icon_name)
    @icon_name = icon_name.to_sym
  end

  def to_s
    "<i class=\"fa-regular fa-#{ERB::Util.html_escape(fontawesome_icon_name)}\"></i>".html_safe
  end

  private def fontawesome_icon_name
    LOOKUP_MAP[@icon_name] || @icon_name
  end
end

app/models/pay_period.rb
class PayPeriod < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true, comparison: { greater_than_or_equal_to: :start_date }
  validate :pay_period_does_not_overlap_existing_periods

  scope :before_date, ->(date){ where("end_date <= :date", date: date) }
  scope :after_date, ->(date){ where("start_date >= :date", date: date) }
  scope :inclusive_of_dates, ->(start_date, end_date){ where("end_date >= :start_date AND start_date <= :end_date", start_date: start_date, end_date: end_date) }

  def start_time
    start_date.beginning_of_day
  end

  def end_time
    end_date.end_of_day
  end

  def update_and_correct_adjacent_pay_periods(new_attribs)
    saved = false

    PayPeriod.transaction do
      assign_attributes(new_attribs)
      # First we delete any periods that have been subsumed by the change
      PayPeriod.where("start_date >= :start_date AND end_date <= :end_date AND id != :id", start_date: start_date, end_date: end_date, id: id).delete_all

      # Second we load any remaining affected periods, and change their dates
      in_scope_periods = PayPeriod.inclusive_of_dates([start_date, start_date_was].min - 1, [end_date, end_date_was].max + 1).where.not(id: self.id)
      in_scope_periods.each do |pay_period|
        if pay_period.start_date < start_date
          pay_period.assign_attributes(end_date: start_date - 1)
        elsif pay_period.end_date > end_date
          pay_period.assign_attributes(start_date: end_date + 1)
        end
      end

      # Last, we check our results. We save without validating, to bypass the
      # pay_period_does_not_overlap_existing_periods validation, then re-check validity before closing the transaction
      in_scope_periods.collect{|pp| pp.save(validate: false) }
      save(validate: false)
      if in_scope_periods.all?(&:valid?) && valid?
        saved = true
      else
        in_scope_periods.each{|pp| puts "#{pp.start_date} - #{pp.end_date} #{pp.errors.inspect}" }
        raise ActiveRecord::TransactionRollbackError
      end
    end
    saved
  end

  private def pay_period_does_not_overlap_existing_periods
    query_scope = PayPeriod
    query_scope = query_scope.where.not(id: self.id) if persisted?
    if query_scope.inclusive_of_dates(start_date, start_date).any?
      errors.add(:start_date, "can't be included in another pay period")
    end
    if query_scope.inclusive_of_dates(end_date, end_date).any?
      errors.add(:end_date, "can't be included in another pay period")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :set_user_time_zone

  private def set_user_time_zone
    # In real life, we check the User record and set it's time zone, but we don't have users yet, so we're gonna default
    # to the dev's time zone.

    Time.use_zone("Pacific Time (US & Canada)") do
      yield
    end
  end
end

app/controllers/pay_periods_controller.rb
class PayPeriodsController < ApplicationController
  # GET /pay_periods
  def index
    @pay_periods = PayPeriod.all
  end

  # GET /pay_periods/calendar
  def calendar
    load_calendar_presenter
  end

  # GET /pay_periods/new
  def new
    set_calendar_start_date
    start_date = params.dig(:pay_period, :start_date) || Date.today
    @pay_period = PayPeriod.new(start_date: start_date, end_date: start_date)
  end

  # GET /pay_periods/1/edit
  def edit
    set_pay_period
    set_calendar_start_date
  end

  # POST /pay_periods
  def create
    @pay_period = PayPeriod.new(pay_period_params)

    if @pay_period.save
      respond_to do |format|
        format.html do
          redirect_to @pay_period, notice: "Pay period was successfully created."
        end
        format.turbo_stream do
          load_calendar_presenter
          render :create
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pay_periods/1
  def update
    set_pay_period
    if @pay_period.update(pay_period_params)
      respond_to do |format|
        format.html do
          redirect_to pay_periods_path, notice: "Pay period was successfully updated.", status: :see_other
        end
        format.turbo_stream do
          load_calendar_presenter
          render :update
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def update_with_adjacent_pay_periods
    set_pay_period
    @pay_period.update_and_correct_adjacent_pay_periods(pay_period_params)
    load_calendar_presenter
    render :calendar
  end

  # DELETE /pay_periods/1
  def destroy
    set_pay_period
    @pay_period.destroy!
    respond_to do |format|
      format.html do
        redirect_to pay_periods_url, notice: "Pay period was successfully destroyed.", status: :see_other
      end
      format.turbo_stream do
        load_calendar_presenter
        render :destroy
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_pay_period
    @pay_period = PayPeriod.find(params[:id])
  end

  private def set_calendar_start_date
    @calendar_start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today
    @calendar_start_date = @calendar_start_date - @calendar_start_date.wday # Align to SUnday
  end

  private def load_calendar_presenter
    set_calendar_start_date
    end_date = @calendar_start_date.advance(weeks: 12) - 1
    @calendar_presenter = PayPeriod::CalendarPresenter.new(
      start_date: @calendar_start_date,
      end_date: end_date,
      pay_periods: PayPeriod.inclusive_of_dates(@calendar_start_date, end_date).all
    )
  end

  # Only allow a list of trusted parameters through.
  private def pay_period_params
    params.require(:pay_period).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.html.erb
<%- unless flash.empty? -%>
  <div id="flash_messages">
    <%- flash.each do |type, msg| -%>
      <div class="<%= type %>">
        <%= Icon.new(type) %>
        <%= msg %>
      </div>
    <%- end -%>
  </div>
<%- end -%>

app/views/layouts/_footer.html.erb
<p>Made by Brent Miller, for Ambiki</p>

app/views/layouts/_header.html.erb
<p class="logo"><%= link_to "Home", root_path %></p>
<nav>
  <%= link_to "Calendar", calendar_pay_periods_path %>
  <%= link_to "Pay periods", pay_periods_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmbikiPayPeriods</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/dc4b902853.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id="content_wrapper">
      <header id="primary_header"><%= render partial: "layouts/header" %></header>
      <%= render partial: "layouts/flash_messages" %>
      <div id="primary_content">
        <%= yield %>
      </div>
      <div id="secondary_content">
        <%= yield :secondary_content %>
      </div>
      <footer id="primary_footer"><%= render partial: "layouts/footer" %></footer>
    </div>
  </body>
</html>

app/views/pay_periods/_calendar.html.erb
<%= turbo_frame_tag "calendar" do %>
  <%- current_pay_period = nil -%>
  <%- cycle_counter = "even" -%>

  <%= calendar(
    number_of_days: @calendar_presenter.number_of_days,
    start_date: @calendar_presenter.start_date,
    turbo_frame_options: {
      data: {
        controller: "calendar",
        calendar_drag_update_path_value: update_with_adjacent_pay_periods_pay_period_path(":id"),
        calendar_calendar_path_value: url_for(start_date: @calendar_presenter.start_date)
      }
    }) do |date| %>
    <span class="date" title="<%= date.to_fs(:long) %>"><%= date.strftime(date.day == 1 ? "%d %b" : "%d") %></span>

    <%- pay_period = @calendar_presenter.pay_period_for_date(date) -%>
    <%- if pay_period.blank? -%>
      <%= link_to "", new_pay_period_path(pay_period: {start_date: date}, start_date: @calendar_presenter.start_date), class: "pay_period_indicator", data: {date: date, turbo_frame: "management_form"} %>
    <%- else -%>
      <%- link_classes = ["pay_period_indicator"] -%>
      <%- if pay_period != current_pay_period -%>
        <%- current_pay_period = pay_period -%>
        <%- cycle_counter = (cycle_counter == "odd" ? "even" : "odd") -%>
        <%- link_classes << "start_of_pay_period" -%>
      <%- end -%>
      <%- link_classes << cycle_counter -%>

      <%= link_to "", edit_pay_period_path(pay_period, start_date: @calendar_presenter.start_date), class: link_classes.join(" "), data: {pay_period_id: pay_period.id, date: date, turbo_frame: "management_form"} %>
    <%- end -%>
  <%- end -%>
<%- end -%>

app/views/pay_periods/_form.html.erb
<%= form_with(model: pay_period) do |form| %>
  <% if pay_period.errors.any? %>
    <div class="errors">
      <ul>
        <% pay_period.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%- if turbo_frame_request? && @calendar_start_date -%>
    <input type="hidden" name="start_date" value="<%= @calendar_start_date %>">
  <%- end -%>

  <div class="fields">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>

    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div class="actions">
    <%- if pay_period.persisted? -%>
      <%= form.submit "Update pay period" %>
      <%= link_to Icon.new(:delete), pay_period_path(@pay_period, start_date: @calendar_start_date), class: "button", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    <%- else -%>
      <%= form.submit "Create pay period" %>
    <%- end -%>
  </div>
<% end %>

app/views/pay_periods/_pay_period.html.erb
<div id="<%= dom_id pay_period %>">
  <%= pay_period.start_date.to_fs(:long) %> &ndash; <%= pay_period.end_date.to_fs(:long) %>
</div>

app/views/pay_periods/calendar.html.erb
<h1>Calendar view</h1>

<%= render partial: "calendar" %>

<%- content_for :secondary_content do -%>
  <h3>Instructions</h3>
  <p>Click on a pay period to edit it, or drag the dark handle at the start of a period to move the boundary</p>
  <p>Click on an empty day to add a <%= link_to "new pay period", new_pay_period_path(start_date: @calendar_presenter.start_date), data: {turbo_frame: "management_form"} %></p>

  <%= turbo_frame_tag "management_form" do %>
  <%- end -%>
<%- end -%>

app/views/pay_periods/create.turbo_stream.erb
<%= turbo_stream.replace "management_form" do %>
  <%= turbo_frame_tag "management_form" do %>
    <span class="notice"><%= Icon.new(:notice) %> Pay period created</span>
  <%- end -%>
<%- end -%>

<%= turbo_stream.replace "calendar" do %>
  <%= render partial: "calendar" %>
<%- end -%>

app/views/pay_periods/destroy.turbo_stream.erb
<%= turbo_stream.replace "management_form" do %>
  <%= turbo_frame_tag "management_form" do %>
    <span class="notice"><%= Icon.new(:notice) %> Pay period deleted</span>
  <%- end -%>
<%- end -%>

<%= turbo_stream.replace "calendar" do %>
  <%= render partial: "calendar" %>
<%- end -%>

app/views/pay_periods/edit.html.erb
<%- if turbo_frame_request? -%>
  <%= turbo_frame_tag "management_form" do %>
    <h3>Edit pay period</h3>
    <%= render "form", pay_period: @pay_period %>
  <%- end -%>
<%- else -%>
  <h1>Editing pay period</h1>

  <%= render "form", pay_period: @pay_period %>

  <div>
    <%= link_to "Back to pay periods", pay_periods_path %>
  </div>
<%- end -%>

app/views/pay_periods/index.html.erb
<h1>Pay periods</h1>

<div class="pay_periods">
  <% @pay_periods.each do |pay_period| %>
    <%= render pay_period %>
    <p class="actions">
      <%= link_to Icon.new(:edit), edit_pay_period_path(pay_period) %>
      <%= link_to Icon.new(:delete), pay_period_path(pay_period), class: "alert", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </p>
  <% end %>
</div>

<%- content_for :secondary_content do -%>
  <%= link_to "#{Icon.new(:add)} New pay period".html_safe, new_pay_period_path, class: "button" %>
<%- end -%>

app/views/pay_periods/new.html.erb
<%- if turbo_frame_request? -%>
  <%= turbo_frame_tag "management_form" do %>
    <h3>New pay period</h3>
    <%= render "form", pay_period: @pay_period %>
  <%- end -%>
<%- else -%>
  <h1>New pay period</h1>

  <%= render "form", pay_period: @pay_period %>

  <div>
    <%= link_to "Back to pay periods", pay_periods_path %>
  </div>
<%- end -%>

app/views/pay_periods/update.turbo_stream.erb
<%= turbo_stream.replace "management_form" do %>
  <%= turbo_frame_tag "management_form" do %>
    <span class="notice"><%= Icon.new(:notice) %> Pay period updated</span>
  <%- end -%>
<%- end -%>

<%= turbo_stream.replace "calendar" do %>
  <%= render partial: "calendar" %>
<%- end -%>

app/views/simple_calendar/_calendar.html.erb
<%= content_tag :div, {class: "simple-calendar"}.merge(calendar.options[:turbo_frame_options] || {}) do %>
  <div class="calendar-heading">
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>

    <nav>
      <%= link_to Icon.new(:go_left), calendar.url_for_previous_view %>
      <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view %>
      <%= link_to Icon.new(:go_right), calendar.url_for_next_view %>
    </nav>
  </div>

  <div class="calendar-grid">
    <% 7.times do |wday| %>
      <div class="calendar-header wday-<%= wday %>"><%= t('date.abbr_day_names')[wday] %></div>
    <%- end -%>

    <% date_range.each_slice(7) do |week| %>
      <% week.each do |day| %>
        <%- css_classes = ["calendar-day", "wday-#{day.wday}"] -%>
        <%- css_classes << "today" if day.today? -%>
        <%- css_classes << "first_of_month" if day == day.beginning_of_month -%>
        <div class="<%= css_classes.join(" ") %>">
          <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
        </div>
      <% end %>
    <% end %>
  </div> <!-- /table-grid -->
<% end -%> <!-- /simple-calendar -->